version: '3.7'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: mobtime
    #container_name: mobtime-webapp
    restart: unless-stopped
    working_dir: /var/www
    command: node -r esm src/fake.js
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    links:
      - redis
    scale: 1
    environment:
      - REDIS_URL=redis://redis

  redis:
    image: redis
    networks:
      - mobtime

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    depends_on:
      - webapp
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

networks:
  mobtime:
    driver: bridge
